### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by kirtiso** [marksteward/rebind#1]
Hello,
I got a error when installing it 
Traceback (most recent call last):
  File "E:\subdomain\rebind-master\rebind.py", line 29, in <module>
    D = DomainName(config.get('rebind', 'root'))
  File "E:\subdomain\rebind-master\ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'rebind'

i don't know how can resolve it.

**Comment by marksteward** [comment]
You'll want to copy rebind.conf.example to rebind.conf and modify it for your purposes.

Also, since I made this, a probably better-tested one has been created at https://github.com/taviso/rbndr. If you're not planning to play around with the python, you might be better of using that (it's already running at rbndr.us).
